import { notFound } from "next/navigation";
import Link from "next/link";
import { Metadata } from "next";
import { services } from "@/data/services";

// All supported service route slugs
const allServiceSlugs = [
  "social-media-management",
  "content-creation",
  "paid-media",
  "growth-strategy",
  "meta-ads",
  "google-ads",
  "cro-automation",
];

export async function generateStaticParams() {
  return allServiceSlugs.map((slug) => ({ slug }));
}

interface Props {
  params: { slug: string };
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const service = services.find((s) => s.slug === params.slug);
  if (service) {
    return {
      title: `${service.title} | ADLUMEO Services`,
      description: service.description,
    };
  }
  if (params.slug === "meta-ads") {
    return {
      title: "Meta Ads & Paid Social | ADLUMEO Services",
      description: "Meta Ads testing, creative vector optimization, and ROAS scaling for growing brands.",
    };
  }
  if (params.slug === "google-ads") {
    return {
      title: "Google Ads & Search Campaigns | ADLUMEO Services",
      description: "High-intent search capture and YouTube video advertising synchronized with social creative.",
    };
  }
  if (params.slug === "cro-automation") {
    return {
      title: "Growth Strategy & Funnel Optimization | ADLUMEO Services",
      description: "Strategic roadmapping and conversion rate optimization for social channels.",
    };
  }
  return { title: "Service Not Found | ADLUMEO" };
}

export default function ServiceDetailPage({ params }: Props) {
  // Find or construct service data
  let currentService = services.find((s) => s.slug === params.slug);

  if (!currentService) {
    if (params.slug === "meta-ads") {
      currentService = {
        id: "03a",
        number: "03A",
        title: "Meta Ads & Advantage+ Scaling",
        slug: "meta-ads",
        subtitle: "Advantage+ Shopping • High-Frequency Creative Vector Testing",
        deliverablesSummary: "Meta Ads Manager, Conversions API, Dynamic Creative",
        description:
          "Meta's ad algorithms require high creative volume to find and convert diverse buyer personas. We build dedicated creative testing funnels that feed the delivery engine with diverse hooks, preventing ad fatigue and stabilizing acquisition costs.",
        deliverables: [
          "Full Advantage+ Shopping and Lead Generation setup",
          "Server-side Meta Conversions API (CAPI) pixel installation",
          "Regular creative variant refreshes (hooks, audio stems, video cuts)",
          "Audience segmentation (Cold Acquisition, Warm Retargeting)",
          "Direct account ownership — client pays Meta ad spend directly with zero agency markup",
        ],
        platforms: ["Instagram", "Facebook", "Meta Audience Network"],
        accentColor: "lime",
      };
    } else if (params.slug === "google-ads") {
      currentService = {
        id: "03b",
        number: "03B",
        title: "Google Ads & Performance Max",
        slug: "google-ads",
        subtitle: "High-Intent Search • YouTube Video Ads • Performance Max",
        deliverablesSummary: "Search Campaigns, YouTube In-Feed, Remarketing",
        description:
          "Harvest high-intent demand generated by social media buzz. We design search and Performance Max campaigns that capture prospective customers actively searching for your product or brand.",
        deliverables: [
          "High-intent keyword architecture and negative matching",
          "Performance Max asset group curation and optimization",
          "YouTube short-form and skippable video ad integration",
          "Enhanced conversion tracking and Google Analytics 4 syncing",
          "Transparent reporting with direct Google billing to client accounts",
        ],
        platforms: ["Google Search", "YouTube", "Performance Max"],
        accentColor: "lime",
      };
    } else if (params.slug === "cro-automation") {
      currentService = services.find((s) => s.slug === "growth-strategy") || services[0];
    } else {
      notFound();
    }
  }

  return (
    <main className="w-full min-h-screen bg-background pt-36 pb-24 px-margin-mobile md:px-margin">
      <div className="max-w-5xl mx-auto flex flex-col gap-16">
        {/* Navigation Breadcrumb */}
        <Link
          href="/services"
          className="inline-flex items-center gap-2 font-label-technical text-xs uppercase text-on-surface-variant hover:text-primary-container transition-colors"
        >
          <span>←</span>
          <span>RETURN TO ALL SERVICES</span>
        </Link>

        {/* Title Header */}
        <div className="border-b border-white/10 pb-10">
          <div className="flex items-center gap-2 font-label-technical text-xs text-primary-container uppercase tracking-widest mb-4">
            <span className="w-2 h-2 bg-primary-container animate-ping"></span>
            SERVICE // {currentService.number}
          </div>

          <h1 className="font-display-hero text-4xl sm:text-6xl lg:text-7xl font-black uppercase text-white tracking-tight leading-[0.95]">
            {currentService.title}
          </h1>
          <p className="font-label-technical text-xs sm:text-sm text-primary-container uppercase tracking-wider mt-4">
            {currentService.subtitle}
          </p>
          <p className="font-body-xl text-lg sm:text-xl text-on-surface-variant max-w-3xl mt-6 leading-relaxed">
            {currentService.description}
          </p>
        </div>

        {/* Deliverables Section */}
        <div className="p-8 sm:p-12 bg-surface-container-low border border-white/10 flex flex-col gap-8">
          <div>
            <span className="font-label-technical text-xs text-primary-container uppercase tracking-widest font-bold block mb-2">
              DELIVERABLES & SCOPE
            </span>
            <h2 className="font-display-hero text-2xl sm:text-3xl uppercase font-bold text-white">
              WHAT IS INCLUDED
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 pt-4 border-t border-white/10">
            {currentService.deliverables.map((item, i) => (
              <div key={i} className="flex items-start gap-3">
                <span className="text-primary-container font-bold text-sm">✓</span>
                <span className="font-body-md text-sm sm:text-base text-white/90 leading-relaxed">
                  {item}
                </span>
              </div>
            ))}
          </div>
        </div>

        {/* Ad Spend & Billing Transparency Callout */}
        <div className="p-6 bg-surface-container-high border-l-4 border-primary-container text-on-surface">
          <span className="font-label-technical text-xs text-primary-container uppercase font-bold block mb-1">
            TRANSPARENT BILLING COMMITMENT
          </span>
          <p className="font-body-sm text-sm text-on-surface-variant leading-relaxed">
            Advertising media spend is paid directly to platforms (Meta, Google, LinkedIn) through your own ad accounts. ADLUMEO charges only for agreed scope (strategy, creative production, and management) — zero markup, zero hidden commissions, and you retain full account ownership.
          </p>
        </div>

        {/* CTA Banner */}
        <div className="p-10 bg-primary-container text-black mt-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-6">
          <div>
            <span className="font-label-technical text-xs uppercase tracking-widest font-black block mb-1">
              READY TO GROW YOUR CHANNELS?
            </span>
            <h3 className="font-display-hero text-2xl sm:text-4xl font-black uppercase">
              GET YOUR FREE SOCIAL GROWTH AUDIT.
            </h3>
          </div>
          <Link
            href="/free-audit"
            className="px-8 py-4 bg-black text-white font-label-technical text-xs font-bold uppercase hover:bg-white hover:text-black transition-all duration-300 whitespace-nowrap shadow-xl"
          >
            GET FREE AUDIT ⚡
          </Link>
        </div>
      </div>
    </main>
  );
}
